name: Deploy to FASTPANEL Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 193.203.160.126 >> ~/.ssh/known_hosts

      - name: Deploy to server
        run: |
          ssh -tt root@193.203.160.126 << 'EOF'
          sudo DEBIAN_FRONTEND=noninteractive apt-get update -y
          sudo DEBIAN_FRONTEND=noninteractive apt-get upgrade -y
          cd /home/fastuser/www/your-domain.com
          git pull origin main
          npm install
          pm2 restart all
          EOF
